name: herewego
description: ""

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  location: ^8.0.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  socket_io_client: ^3.1.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  webview_flutter: ^4.13.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true